name: Mathics3-django (MacOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        brew install llvm@14 nodejs npm tesseract
        python -m pip install --upgrade pip
    - name: Install Python dependencies
      run: |
        # Can adjust when next Mathics3 is released
        git clone --depth 1 https://github.com/Mathics3/Mathics3-scanner.git
        cd Mathics3-scanner/
        pip install -e .
        bash -x admin-tools/make-JSON-tables.sh
        cd ..
        git clone --depth 1 https://github.com/Mathics3/mathics-core.git
        cd mathics-core/
        pip install -e .
        bash -x admin-tools/make-JSON-tables.sh
        cd ..
        npm install
    - name: Install Mathics3 Django
      run: |
        # We will do full after release of the various Mathics3 Modules
        # pip install -e .[full]
        pip install -e .
        make develop
    - name: Test Mathics3 Django
      run: |
        make check
