name: Mathics-Django (OSX)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        brew install llvm@11 nodejs npm tesseract
        python -m pip install --upgrade pip
        LLVM_CONFIG=/usr/local/Cellar/llvm@11/11.1.0/bin/llvm-config pip install llvmlite
    - name: Install Python dependencies
      run: |
        # Can comment out when next Mathics is released
        # python -m pip install -e git+https://github.com/Mathics3/mathics-scanner#egg=Mathics-Scanner[full]
        # git clone https://github.com/Mathics3/mathics-core
        # (cd mathics-core && make)
        # (cd mathics-core && python -m pip install -e .[full])
        pip install Mathics[full]
    - name: Install Mathics3 Django
      run: |
        npm install
        pip install -e .[full]
        pip install pytest pexpect
        make develop
    - name: Test mathics-django
      run: |
        make check
