name: Mathics-Django (OSX)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew install llvm@11 remake nodejs npm
        python -m pip install --upgrade pip
        LLVM_CONFIG=/usr/local/Cellar/llvm@11/11.1.0/bin/llvm-config pip install llvmlite
        # Can comment out when next Mathics is released
        python -m pip install -e git://github.com/mathics/Mathics#egg=Mathics3[full]
        npm install
        pip install -e .[full]
    - name: Install Mathics Django
      run: |
        remake -x develop
    - name: Test mathics-django
      run: |
        pip install pytest pexpect
        remake -x check
